### PR TITLE
Synching up to changes made in agenda 0.7.2.

### PR DESCRIPTION
**Pull request by 3choBoomer**
-Added better error checking in constructor.

Agenda 0.7.2 renamed _db to _collection to better match what the variable actually holds.

### CODE REVIEW

**Comment by esteban-uo** [comment]
@3choBoomer thanks!, @moudy can you please merge this? thanks!

**Comment by niftylettuce** [comment]
@moudy @esteban-uo @3choBoomer can you please merge this?

**Comment by liamdon** [comment]
:+1:

**Comment by niftylettuce** [comment]
@liamdon Hey Liam :smile: nice to see you here!  Hope ClassDojo is going well.

**Comment by niftylettuce** [comment]
There is only one working use case with this pull request:

```js
var agenda = new Agenda({ mongo: myMongoClientConnection });
```

This does not work:

```js
var agenda = new Agenda({ db: { address: myDBURIString, collection: 'agendaJobs'} });
```

@3choBoomer can we get this patched to support this usage too?

**Comment by niftylettuce** [comment]
This is the error we get if we don't use `mongo` as an option:

```log
  if (!agenda._collection) {throw new Error('_collection is undefined. Check a
                                  ^
Error: _collection is undefined. Check agenda config.
    at new module.exports (/Users/niftylettuce/Public/agenda-ui-test/node_modules/agenda-ui/lib/store.js:6:35)
    at module.exports (/Users/niftylettuce/Public/agenda-ui-test/node_modules/agenda-ui/lib/api.js:6:15)
    at module.exports (/Users/niftylettuce/Public/agenda-ui-test/node_modules/agenda-ui/index.js:38:11)
    at Object.<anonymous> (/Users/niftylettuce/Public/agenda-ui-test/agenda-ui.js:22:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by pmettraux** [comment]
need that one to be merged please

**Comment by pruhstal** [comment]
+1, please merge :)

**Comment by jeonghwan-kim** [comment]
+1, merge please

**Comment by 3choBoomer** [comment]
@niftylettuce done.

**Comment by niftylettuce** [comment]
thanks, just needs merged now

**Comment by 3choBoomer** [comment]
we need @moudy to do that.

**Comment by moudy** [comment]
@3choBoomer sorry just seeing this now, thanks!

**Comment by moudy** [comment]
@3choBoomer having trouble getting the project to build so can't publish to NPM yet... will try to find time to debug soon.

**Pull request merged**
